fix pandas warning in application of risk effect
ihmeuw/vivarium_public_health pull request #237
Opened 2021-08-20 20:09 UTC by rmudambi

Verified that functionality is the same using `vivarium_ciff_sam`. Also verified that `lookup` is not used anywhere else in the repo

2021-08-20 21:07 UTC, KjellSwedin approved these changes

2021-08-20 21:46 UTC, mattkappel approved these changes

2021-08-20 21:48 UTC, KjellSwedin approved these changes

2021-08-24 21:59 UTC, collijk requested changes
look at my review

2021-08-24 21:59 UTC, collijk commented on src/vivarium_public_health/risks/data_transformations.py
> +            exposure = pd.Series(risk_exposure(rr.index), name=risk.name)
test

2021-08-24 21:59 UTC, collijk commented on src/vivarium_public_health/risks/data_transformations.py
> +            effect = rates * df.apply(lambda x: x[x[risk.name]], axis=1)
test2

2021-08-31 23:08 UTC, mattkappel approved these changes

2021-08-31 23:13 UTC, KjellSwedin approved these changes

2021-08-31 23:16 UTC, merged