Mic 4180/doc builds
ihmeuw/vivarium_public_health pull request #351
Opened 2023-09-12 21:51 UTC by albrja

## Mic 4180/doc builds

### Update URL to VPH in build.yml
- *Category*: Documentation
- *JIRA issue*: [MIC-4180](https://jira.ihme.washington.edu/browse/MIC-4180)

### Changes and notes
-update url to VPH instead of vivarium in build.yml

### Testing

2023-09-12 22:04 UTC, rmudambi requested changes

2023-09-12 22:04 UTC, rmudambi commented on .github/workflows/build.yml
This change is incorrect. We do want this to read vivarium. This is looking to see if vivarium has a branch with the same name as the PRed VPH branch, and to check that branch out instead of `main` if it does exist.

2023-09-12 22:56 UTC, mattkappel approved these changes

2023-09-14 21:09 UTC, rmudambi approved these changes

2023-09-14 21:55 UTC, merged