Remove python3.8
ihmeuw/vivarium_public_health pull request #366
Opened 2023-10-05 21:49 UTC by hussain-jafari

remove python3.8

2023-10-05 22:03 UTC, patricktnast commented
I'm not sure how much this matters, but we also have a hard-coded reference to python 3.8 in https://github.com/ihmeuw/vivarium_public_health/blob/65251452bb3e4826da165716140cd56947e97247/docs/source/conf.py#L198

2023-10-05 22:05 UTC, patricktnast approved these changes

2023-10-05 23:07 UTC, rmudambi approved these changes

2023-10-05 23:07 UTC, rmudambi commented on CHANGELOG.rst
> + - No longer using Python 3.8
Nit: I'd call this "Remove explicit support for Python 3.8"

2023-10-05 23:07 UTC, rmudambi commented on .github/workflows/build.yml
> +        python-version: ["3.9", "3.10", "3.11"]
Did you try adding 3.12 and see if it builds?

2023-10-05 23:26 UTC, rmudambi commented
You will also need to remove 3.8 (and add 3.12 if we go that route) to the status checks that need to pass in order to merge

2023-10-09 17:39 UTC, rmudambi approved these changes

2023-10-09 21:58 UTC, rmudambi requested changes

2023-10-09 21:58 UTC, rmudambi commented on CHANGELOG.rst
> + - Minor bugfix to ensure default remission rate calls the right artifact key
Did we actually release VPH 2.0.2? I didn't think we did. If we didn't, this information should be additional bullet point in the 2.1.0 release.

2023-10-10 16:34 UTC, rmudambi approved these changes

2023-10-10 17:16 UTC, merged