Mic 2585/population config keys
ihmeuw/vivarium_public_health pull request #386
Opened 2024-03-07 00:12 UTC by albrja

## Mic 2585/population config keys

### Updates BasePopulation configuration keys to be more description.
- *Category*: Feature
- *JIRA issue*: https://jira.ihme.washington.edu/browse/MIC-2585

### Changes and notes
-updates configuration keys to initialization_age_min, initialization_age_max, and untracked_age.
-Adds deprecation warning for old configuration keys

### Testing
All tests pas

2024-03-07 01:18 UTC, rmudambi requested changes

2024-03-07 21:20 UTC, rmudambi approved these changes

2024-03-08 00:09 UTC, stevebachmeier commented on src/vivarium_public_health/population/base_population.py
> +                    f"These keys cannot both be provide. '{key}' will soon be deprecated so please "
typo: provideD

2024-03-08 00:10 UTC, stevebachmeier approved these changes

2024-03-08 00:25 UTC, merged