Bugfix/sbachmei/transition names to str
ihmeuw/vivarium_public_health pull request #446
Opened 2024-07-08 19:56 UTC by stevebachmeier

## Coerce transition names to str

### Description

- *Category*:  bugfix
- *JIRA issue*: na

### Changes and notes
 
We found that when using psimulate, we were getting a runtime error
when deserializing. It seems that the DiseaseObserver categories
(which were TransitionSTrings) were getting instantiated again
using their repr which causes an error - see https://jira.ihme.washington.edu/browse/MIC-5149

### Testing

Ran a small psimulate with the mnch maternal model

2024-07-08 20:29 UTC, hussain-jafari approved these changes

2024-07-08 20:32 UTC, hussain-jafari requested changes
failing tests

2024-07-08 23:19 UTC, albrja approved these changes

2024-07-09 17:17 UTC, hussain-jafari approved these changes

2024-07-09 17:18 UTC, merged